.TH MYSTRNCPY 3 "September 2026" "OS Assignment" "Library Functions"
.SH NAME
mystrncpy \- copy up to a specified number of characters
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.PP
.BI "int mystrncpy(char *" dest ", const char *" src ", int " n ");"
.SH DESCRIPTION
The
.B mystrncpy
function copies up to
.I n
characters from the string pointed to by
.I src
into the buffer pointed to by
.IR dest .
The destination buffer must have enough space for the copied characters.
.SH RETURN VALUE
Returns the number of characters copied.
.SH SEE ALSO
.BR mystrlen (3),
.BR mystrcpy (3),
.BR mystrcat (3)
.SH AUTHOR
Sadia Mushtaq <BSDSF24M036@PUCIT.EDU.PK>
